### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by SamaraFellaDina** [KaanKalmi/S10-enhanced-website#1]
### [`server.js`](https://github.com/KaanKalmi/S10-enhanced-website/blob/main/server.js)
* Ik zou overbodige aantekeningen weghalen

Meer kan ik voor nu niet zeggen

![](https://media.giphy.com/media/ShIhLXpzHbjVLBuQHg/giphy.gif?cid=790b7611g4kw1phdwbn4m64o9g42dlsgw2y8dyi4j4wynxls&ep=v1_gifs_trending&rid=giphy.gif&ct=g)

**Comment by KaanKalmi** [comment]
overbodige aantekeningen zijn weggehaald 


<img src="https://github.com/KaanKalmi/S10-enhanced-website/assets/144000125/5a5cd124-02a4-4e33-afaa-ab77470bf95f" width=750>
