### ISSUE TITLE
Well done with performace

### ISSUE THREAD

**Issue by christoph3r3w** [KaanKalmi/S10-enhanced-website#4]
Your site scored well . there was no issue with layout-shifting, loading optimization, and responsive images.

my only tip is to pay attention to your mobile layout  

https://pagespeed.web.dev/analysis/https-s10-gflo-onrender-com/qrsov7fxo1?form_factor=mobile

<img width="400" alt="" src="https://github.com/KaanKalmi/S10-enhanced-website/assets/144007933/a7f8909c-10c4-492c-bfa1-04ccb4562caa">

<img width="400" alt="" src="https://github.com/KaanKalmi/S10-enhanced-website/assets/144007933/92f08c8d-c1c3-4c04-9886-cdf4c5ea6147">

**Comment by KaanKalmi** [comment]
mobile layout will be done in the next sprint
